name: fasting 

environment:
  sdk: ^3.9.0

# TODO: Use glob here
workspace:
  - packages/application/fasting_use_cases
  - packages/application/notifications_service
  - packages/domain/fasting_entities
  - packages/domain/repositories/fasting_repository
  - packages/domain/repositories/settings_repository
  - packages/infrastructure/settings_api
  - packages/infrastructure/local_fasting_api
  - packages/infrastructure/local_settings_api
dev_dependencies:
  melos: ^7.3.0
